# Generated by Django 4.0.3 on 2022-04-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customer_user_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix',
        ),
    ]
